Apply velocity boundary conditions
cb-geo/mpm pull request #255
Opened 2018-09-15 00:50 UTC by ezrayst

- [ ] Proposed is the structure
- [ ] Add `Geometry` class in `cell`
- [ ] Make the function to apply 
- [ ] Make test functions

2018-09-15 09:33 UTC, kks32 requested changes
Could you please explain how the nodal velocities are getting updated here?

2018-09-15 09:33 UTC, kks32 commented on include/cell.h
> +  //! Parallel of face
What do you mean by `parallel of face`?

2018-09-15 09:33 UTC, kks32 commented on include/cell.h
> +  std::map<unsigned, Eigen::VectorXd> constrained_nodal_velocity_;
`nodal_velocity_constraints_`

2018-09-15 09:33 UTC, kks32 commented on include/cell.h
> +  std::map<unsigned, Eigen::VectorXd> constrained_nodal_acceleration_;
`nodal_acceleration_constraints_`

2018-09-15 09:33 UTC, kks32 commented on include/cell.h
> +  std::unique_ptr<Geometry<Tdim>> geometry_ =
Geometry is not an object, and it shouldn't be an object.

2018-09-15 09:33 UTC, kks32 commented on include/cell.tcc
> +void mpm::Cell<Tdim>::apply_velocity_constraints() {
Can you not pass the `phase` here?

2018-09-15 09:33 UTC, kks32 commented on include/cell.tcc
> +  for (auto iterator = this->velocity_constraints_.begin();
Use `itr`

2018-09-15 09:33 UTC, kks32 commented on include/cell.h
> +  std::map<unsigned, Eigen::VectorXd> constrained_nodal_velocity_;
You already have `velocity_constraints_`, why do you need these two? why can't be local to the apply velocity constraints function?

2018-09-15 09:33 UTC, kks32 commented on include/cell.tcc
> +  for (unsigned i = 0; i < this->nfunctions(); ++i) {
Why do we need to copy this information from the nodes, is it not sufficient to tell the nodes what the velocities and accelerations should be? You shouldn't need to know what the velocity currently is, to do this.

2018-09-15 09:33 UTC, kks32 commented on include/cell.h
> +  std::map<unsigned, Eigen::MatrixXd> new_coordinate_axes_;
Do you mean to say it as the local co-ordinates?

2018-09-15 09:33 UTC, kks32 commented on include/cell.tcc
> +      // const auto phase = static_cast<unsigned>(dir / Tdim);
any reason why you can't do phase?

2018-09-15 09:33 UTC, kks32 commented on include/cell.tcc
> +        // Rotate velocity and acceleration vectors to new coordinate axes
You are resetting this value three lines below, why are we doing this?

2018-09-15 09:33 UTC, kks32 commented on include/cell.tcc
> +      // Apply it to the nodes
I can't see it being applied to any node here! There is no access to a single nodal pointer. Am I missing something?

2018-09-15 22:19 UTC, kks32 requested changes
Ignore this!

2018-09-16 11:20 UTC, kks32 requested changes

2018-09-16 11:20 UTC, kks32 commented on include/cell.tcc
> +            rotation_matrix.inverse();
Can we take the transpose instead?

2018-09-16 11:20 UTC, kks32 commented on include/cell.tcc
> +        constrained_nodal_velocity_[node_indices(j)] *= rotation_matrix;
Why aren't we returning these variables, why is it stored in the cell level?

2018-09-19 23:16 UTC, ezrayst commented
Proposed structure of the code for applying velocity boundary:
- [ ] The input file would still contain boundary constraints on `face`
- [ ] Boundary constraints are stored in `cell` because we need the data of the `face`
- [ ] Make a proxy to indicate the boundary are defined at the `face` or by the `nodes`
- [ ] Node's `compute_acceleration_velocity` should contain `apply_velocity_boundary` for node-based or cell-based boundary
- [ ] In cell based, we have to iterate through all the faces this boundary: (1) rotate the current velocity, (2) apply all boundaries in new local coordinate system, (3) rotate back to Cartesian

Note the following:
- Using Krishna's example of isoparametric Element 0 and Element 1, and roller support on both bottom faces, node 0 would not be constrained to move in all directions, so this method of applying boundary is, in my opinion, sound. 
- Using resultant to apply boundary would not be right, I think, as we are forcing certain components to be zero, which are not equivalent of making the resultant of that zero.

2018-09-19 23:35 UTC, kks32 commented
* How do you plan to achieve ` Make a proxy to indicate the boundary are defined at the face or by the nodes`?

* I'd suggesting a boolean at the node to have `cell_velocity_constraints_` if true, we apply those. 

* Ideally it would be better for the node to have access, not necessarily store, all the constraints. If we do that, then it is easier to iterate.

* We need to consider the special case of 0, when zero velocity is applied on more than one direction, that plane will have zero velocity. Does this make it computationally faster? 

* We should never do resultant, rather it should be a linear summation of all constraints at a node.

2018-09-19 23:40 UTC, kks32 commented
Could you provide more information on what kind of data structure will be used to store the constraints at the cell and the node level?

2018-09-20 00:10 UTC, ezrayst commented
- I am fine with `boolean` for `cell_velocity_constraints_`
- The nodes could have access, but the `face_id` should dictate it. `face_id` will give local numbering (cell level) of the nodes, which I think we can map to the global nodes.
- After thinking about it again, we should not apply boundary when calculating the acceleration and velocity. I think it's cleaner to apply them after all nodes have been calculated. So we iterate over all the constraints and apply them to all nodes.
- Agree on the resultant

> * We need to consider the special case of 0, when zero velocity is applied on more than one direction, that plane will have zero velocity. Does this make it computationally faster?
On this, I think let's just apply it as it is, then we can optimize later. What do you think? 

Data Structure:
- Storing constraints would remain the same for cell level now, which is a `std::map<unsigned, std::vector<std::pair<unsigned, double>>>` with the key being `face_id`, and the pair containing `direction` in new local coordinate and the value of the velocity
- I don't think we need to store the nodes. We just iterate over the `map`, and for each `face_id`, we will get all the affected local `node_id`, map them to global `node_id` and apply to all affected nodes
- Note that at each `apply` include: (1) rotate current velocity and acceleration, (2) apply the values of velocities and accelerations, (2) rotate back. So velocity and acceleration are always in Cartesian coordinate

2018-09-20 00:21 UTC, kks32 commented
We apply nodal velocity constraints on Cartesian grids at the time of computation of acceleration and velocity, this way, when velocity is calculated at the node we always get the right velocity. I don't see why inclined constraints can't be applied at the same time. I do not get the argument of it being clean, because doing so will return velocities and accelerations which are incorrect (before restraints are applied). That's not good.

Nodes having access to all its constraints means we can optimise for the case of zero. Doing at the cell level, we won't have enough information to find which two planes have zero velocity. To me, node should have access to all the constraints, and this should be done at the assign_cell_constraints step. 

Let me know if you think this won't work.

2018-09-20 00:23 UTC, kks32 commented
I'm not clear about `The nodes could have access, but the face_id should dictate it. face_id will give local numbering (cell level) of the nodes, which I think we can map to the global nodes.`, how this mapping will be done, what information will be transferred to the nodes, how and when will it be done?

2018-09-20 00:28 UTC, kks32 commented
`I don't think we need to store the nodes. We just iterate over the map, and for each face_id, we will get all the affected local node_id, map them to global node_id and apply to all affected nodes` This would require adding an extra function and ensuring that this function is definitely called before returning the nodal velocities and acceleration. There is no guarantee that someone might forget to call this function, and hence will get unconstrained velocities and accelerations.

2018-09-20 00:34 UTC, ezrayst commented
Well, let's agree that the velocity boundaries will be defined on the face. Is this good? I don't see how we can do better in the other ways. 

If we are good on this, and you want to apply velocity and acceleration as we calculate them, we have to transfer those `face` velocities to `node` velocities, and use the latter when we apply them. We can write a function for this in `cell` to do that, which calls on something like `assign_cell_velocity_boundary` in `node` to store. I think the data structure should be a map of direction and a pair of direction and values.

But we are back at the issue I raised just now, about mapping from local node number we have from the face, to the global when we store them in `node`. What do you think?

2018-09-20 01:00 UTC, kks32 commented
`Well, let's agree that the velocity boundaries will be defined on the face. Is this good? I don't see how we can do better in the other ways.`
- Agree the velocity boundaries for inclined planes have to be applied on the face. For each face constraint, we could store the rotation matrix, direction and constraint velocity at the cell level as a map with key being the faceid.

`If we are good on this, and you want to apply velocity and acceleration as we calculate them, we have to transfer those face velocities to node velocities, and use the latter when we apply them. `
 - Agree we need to transfer it to the nodes, so each shared node with cell velocity constraints has all the information it needs. 

`We can write a function for this in cell to do that, which calls on something like assign_cell_velocity_boundary in node to store. I think the data structure should be a map of direction and a pair of direction and values.`
- Why not use the `assign_cell_velocity_constraints` function to create and assign the constraints to the nodes, why need a new function?

`But we are back at the issue I raised just now, about mapping from local node number we have from the face, to the global when we store them in node. What do you think?`
- I don't see any issue here, the cell has nodal pointers, what is the problem?

2018-09-20 02:53 UTC, ezrayst commented
> Agree the velocity boundaries for inclined planes have to be applied on the face. For each face constraint, we could store the rotation matrix, direction and constraint velocity at the cell level as a map with key being the faceid. This might reduce the number of times we calculate the rotation matrix at each node. For each cell with a face constraint, we have to do it at least 4 times. Storing it means we do it once. It's a balance between size vs efficiency. Since the shape of the cell doesn't change, it's better to store the rotation matrix, than to calculate it at each step.
- Yes, we need the rotation matrix too. I will add the `rotation matrix` as well to the map then.

> Why not use the assign_cell_velocity_constraints function to create and assign the constraints to the nodes, why need a new function?
- Agree, we can use that function as well. 

> I don't see any issue here, the cell has nodal pointers, what is the problem?
- I see! I am OK then. I can work with that


Then all we have is the `apply` part. I guess we will use `if` function. If we have `rotation matrix`, then we will rotate, apply and rotate back. If not, we will simply apply it as is.

When we have more phases, we will follow the current scheme with directions of 4, 5, 6 etc. That would be checked only when nodal constraint is passed to `nodes`, and would not be checked at `cell` because it does not have `Tnphases`. Would this be OK?

2018-09-20 14:40 UTC, kks32 commented
`Yes, we need the rotation matrix too. I will add the rotation matrix as well to the map then.`
- Create a map to a shared_pointer to a struct object for constraint.

2018-09-20 18:46 UTC, ezrayst commented
The struct object means the map containing rotation matrix, direction and velocity value?

2018-09-20 18:47 UTC, kks32 commented
How are you planning to store `rotation matrix, direction and velocity`?

2018-09-20 19:03 UTC, ezrayst commented
I was thinking of a `map` of a `tuple`. The key is `face_id` and the tuple would consist `Eigen::MatrixXd rotation matrix`, `unsigned direction`, and `double velocity value`. So:
- `cell` stores a map with key: `face_id`, and the `tuple` as described above
- we make another private variable in `node` called `face_velocity_constraints_` which is a `vector` of `tuple` containing `rotation matrix` and a pair of `direction` and `velocity`.
- we have another function to `assign` to node constraint
- In `apply`, we can have `boolean` to see whether `face_velocity_constraints_` are empty. If it is, then go with the node scheme, otherwise, go with the cell-node scheme

2018-09-20 19:11 UTC, kks32 commented
This would mean the rotation matrix and the constraints will be copied redundantly from cells to each node in which the constraint is applied. If we assume the rotation matrix has 9 components of doubles, that's 9 * 8 bytes * 4 (nodes on a face) 288 bytes of redundant storage just for the rotation matrices. Tuples are not the best way to pass the constraints from cell to nodes.

2018-09-20 19:23 UTC, ezrayst commented
> Create a map of face_id to a shared_pointer of a struct object for the constraint.
- So you mean to have pointer to the whole `cell`? I don't quite get it

2018-09-20 19:37 UTC, kks32 commented
You can have a pointer to a constraint object. Create a constraint object in the cell, store it as a map <face_id, ptr_to_constraints>, `Nodes` have  a vector of pointers to constraints.

2018-09-20 19:37 UTC, ezrayst commented
I will try then. Let me try to implement.

2018-09-20 19:40 UTC, ezrayst commented
Wait, I will wait until our meeting today, then I will work on it again.

2018-09-20 22:37 UTC, kks32 commented
Closing this PR as Velocity constraints have to be redesigned to be mapped directly from cell to nodes.

2018-09-20 22:37 UTC, closed without merging