Fix GIMP #281
cb-geo/mpm pull request #282
Opened 2018-10-09 12:01 UTC by cw646

Changes to cell and particle calls of shapefn and bmatrix, add missing call to tnfunctions in gimp header.

2018-10-09 12:11 UTC, kks32 requested changes

2018-10-09 12:11 UTC, kks32 commented on include/cell.tcc
> +  if (element_->shapefn_type() == mpm::ShapefnType::GIMP) {
It doesn't matter if it is GIMP or CPDI it's the same call.

2018-10-09 13:12 UTC, kks32 requested changes
Add tests in particle class to check for both normal and special shape function calls

2018-10-10 10:39 UTC, cbgeo commented
Superseded by #285 . Closing without merge.

2018-10-10 10:39 UTC, closed without merging