Pressure smoothing
cb-geo/mpm pull request #324
Opened 2018-10-31 01:07 UTC by ezrayst

- [x] Implement pressure smoothing which involves mapping and average weight.
- [x] test cases are made

![image](https://user-images.githubusercontent.com/22064721/47759786-77400e00-dc6e-11e8-876c-3711c1981ee4.png)

Results: (top is normal, bottom is with pressure smoothing)
![Uploading image.png…]()

2018-10-31 06:52 UTC, kks32 requested changes
- [ ] Pressure smoothing should be an optional argument that should be disabled by default.
- [ ] You need an MPI all_reduce scalar on the pressure term
- [ ] How does pressure smoothing work when more than a single material type is used, does it affect all the materials? Shouldn't it only smooth those where pressure can be computed?
- [ ] Need both USF and USL to be updated

2018-10-31 06:52 UTC, kks32 commented on include/mpm_explicit_usf.tcc
> +
Need an MPI all_reduce call here

2018-10-31 06:52 UTC, kks32 commented on include/mpm_explicit_usf.tcc
> +    // Assign pressure to nodes
This whole block should be optional and done only if pressure_smoothing is enabled

2018-11-07 07:17 UTC, ezrayst commented on include/mpm_explicit_usf.tcc
> +    }
I can't use `std::placeholders::_3` for some reason. Note that `update_pressure` has 4 input arguments: `update boolean`, `phase`, `mass` and `pressure`.

2018-11-07 07:20 UTC, ezrayst commented
I am not sure about what to do with different material id currently. Do we have only a pressure for all the phases? What if we have `Bingham` for solid and `Newtonian` for fluid in 2-phase MPM?

2019-03-28 03:20 UTC, kks32 commented
#396 supersedes this PR so closing

2019-03-28 03:20 UTC, closed without merging