Mc model
cb-geo/mpm pull request #350
Opened 2019-01-14 18:31 UTC by srhgk2

Add new modified mohr coulomb material model. There is still work remaining in the softening part.

2019-01-15 19:31 UTC, kks32 requested changes

2019-01-15 19:31 UTC, kks32 commented on include/material/mohr_coulomb.h
> +//! \brief Linear Elastic material model
MohrCoulomb

2019-01-15 19:31 UTC, kks32 commented on include/material/mohr_coulomb.h
> +  bool compute_rho_theta(const Vector6d stress, double& _j2, double& _j3,
Could we have `j2`, `j3`, `rho`, `theta` and `softening` as private variables in the class, instead of passing around in the functions?

2019-01-15 19:31 UTC, kks32 commented on include/material/mohr_coulomb.h
> +  double c_{std::numeric_limits<double>::max()};
Is this cohesion `c_` different from `cohesion_`?

2019-01-15 19:31 UTC, kks32 commented on include/material/mohr_coulomb.tcc
> +  const double ONETHIRDPI = 1.047197551;
Needs more digits for double

2019-01-15 19:31 UTC, kks32 commented on include/material/mohr_coulomb.h
> +  void compute_rho_theta(const Vector6d& stress);
We need to add `\param` parameters

2019-01-15 19:31 UTC, kks32 commented on include/material/mohr_coulomb.tcc
> +  const double ONETHIRDPI = 1.047197551;
needs more digits

2019-01-18 18:37 UTC, srhgk2 commented on include/material/mohr_coulomb.h
> +  bool compute_rho_theta(const Vector6d stress, double& _j2, double& _j3,
Yes, let's do.

2019-01-18 18:39 UTC, srhgk2 commented on include/material/mohr_coulomb.h
> +  double c_{std::numeric_limits<double>::max()};
We need three values for each plastic parameters, (psi, phi and c). Two constant values for peak and residual parameters. And another value which is the current value depending on the hardening model.

2019-01-18 18:42 UTC, srhgk2 commented on include/material/mohr_coulomb.h
> +  double c_{std::numeric_limits<double>::max()};
So, yes `cohesion_` is different from `c_`.

2019-01-18 18:42 UTC, srhgk2 commented on include/material/mohr_coulomb.tcc
> +  const double ONETHIRDPI = 1.047197551;
got it.

2019-01-18 19:22 UTC, kks32 commented on include/material/mohr_coulomb.h
> +  bool compute_rho_theta(const Vector6d stress, double& _j2, double& _j3,
I have made that change.

2019-02-09 15:13 UTC, kks32 commented
Newer version #363

2019-02-09 15:13 UTC, closed without merging