Mc model
cb-geo/mpm pull request #358
Opened 2019-02-02 07:09 UTC by z149181511

2019-02-02 07:12 UTC, z149181511 commented
add: 
1) softening part
2) tension  cutoff
3) check the load/unload process

2019-02-02 15:03 UTC, kks32 requested changes
@z149181511 Could you please rebase to https://github.com/cb-geo/mpm/tree/mc_model otherwise it undoes all the changes to variable names and function call I did 10 days ago.

Please note: all variables and function names should be lower case. Only classes can have upper case. Please see:  https://cb-geo.github.io/cpp-guide/#/naming/naming_rules. 

`_` at the end of the variable so `j2_` means it's a private variable, please don't use `_` before a variable name.

2019-02-02 15:03 UTC, kks32 commented on include/material/mohr_coulomb.h
> +  //! tracke the equivalent_plastic_deviatoric_strain
```suggestion
  //! Equivalent plastic deviatoric strain
```

2019-02-02 15:03 UTC, kks32 commented on include/material/mohr_coulomb.h
> +  double epds_last = 0.;
```suggestion
  double epds_last_{0.};
```

2019-02-02 15:03 UTC, kks32 commented on include/material/mohr_coulomb.h
> +  double epds_last = 0.;
What do you mean by last?

2019-02-02 15:03 UTC, kks32 commented on include/particle.h
> +  Eigen::Matrix<double, 6, 1> PDS_;
```suggestion
  Eigen::Matrix<double, 6, 1> epsilon_pd_;
```

2019-02-02 15:03 UTC, kks32 commented on include/material/mohr_coulomb.tcc
> +    ptr-> update_PDS(PDS);
This works!? Shouldn't ptr be a const?

2019-02-05 22:26 UTC, srhgk2 requested changes
There are two thing I would like to discuss. Could you please see the comments and explain?

2019-02-05 22:26 UTC, srhgk2 commented on include/material/mohr_coulomb.tcc
> +  phi_ = phi_max; psi_ = psi_max; c_ = c_max;
It looks to me as at every time step, `phi_`, `psi_` and `c_` have been set to peak values which are used to compute the tension-shear edge. Can you explain if this is correct?

2019-02-05 22:26 UTC, srhgk2 commented on include/material/mohr_coulomb.tcc
> +  const double epds = (2. / 3.) * sqrt(3. / 2. * (PDS(0) * PDS(0) + PDS(1) * PDS(1) + PDS(2) * PDS(2))
Computing `epds`: does it make a difference when epds is computed at the end and storing it at particle? Because it would be better to store `epds` at particle. It seems to me that it would give the same results.

2019-02-06 18:18 UTC, srhgk2 commented on include/material/mohr_coulomb.tcc
> +  const double epds = (2. / 3.) * sqrt(3. / 2. * (PDS(0) * PDS(0) + PDS(1) * PDS(1) + PDS(2) * PDS(2))
Following our discussion, let's compute `epds` at the end and store it at particles.

2019-02-06 18:21 UTC, srhgk2 commented on include/material/mohr_coulomb.tcc
> +  phi_ = phi_max; psi_ = psi_max; c_ = c_max;
As discussed, `phi_`, `psi_` and `c_` will be initialized to its peak values when the analysis begins.

2019-02-07 00:43 UTC, srhgk2 commented on include/material/mohr_coulomb.tcc
> +  if(epds_last < peak_EPDS_ && epds > peak_EPDS_)softening = 0;
TO DO: use of `epds_last`needs further clarification.

2019-02-07 00:43 UTC, srhgk2 commented on include/material/mohr_coulomb.tcc
> +    if(yield_type == 1 && dyfun_t > 0){
It looks both `if` statements do the same thing? Can we instead have it inside one `if` statement?

2019-02-09 15:14 UTC, kks32 commented
#363 replaces this PR

2019-02-09 15:14 UTC, closed without merging