:bug: Fixed bug causing MPI to crash when running pressure smoothing
cb-geo/mpm pull request #405
Opened 2019-04-16 00:20 UTC by cw646

The division of mass_pressure by mass when MPI update called was causing simulation failure

2019-04-16 09:53 UTC, cw646 commented
Need to fix tests

2019-04-21 21:57 UTC, kks32 requested changes

2019-04-21 21:57 UTC, kks32 commented on include/node.tcc
> +void mpm::Node<Tdim, Tdof, Tnphases>::update_pressure(bool update,
This is assign pressure because you are merely assigning the value here

2019-05-23 21:38 UTC, kks32 commented
#426 supersedes this PR

2019-05-23 21:38 UTC, closed without merging