Added 3D gimp functionality
cb-geo/mpm pull request #447
Opened 2019-07-04 15:46 UTC by cw646

![gimp_numbering](https://user-images.githubusercontent.com/22824571/60678062-3a6e8b80-9e7b-11e9-8eeb-ef4878030619.png)

See 3D GIMP node numbering above

2019-07-04 17:05 UTC, cw646 commented on include/hexahedron_gimp_element.tcc
> +    }
tweak ordering

2019-07-07 17:44 UTC, kks32 commented on include/hexahedron_gimp_element.tcc
> +    return shapefn;
Could you print out what the exception would be?
```
console_->error("{} # {}: {}", __FILE__, __LINE__, exception.what());
```

2019-11-06 16:22 UTC, kks32 requested changes

2019-11-06 16:22 UTC, kks32 commented on include/hexahedron_gimp_element.tcc
> +    return shapefn;
@cw646 could you do this please?

2019-11-06 16:22 UTC, kks32 commented on include/hexahedron_gimp_element.tcc
> +    }
And this?

2019-11-25 17:42 UTC, kks32 approved these changes

2019-11-26 03:50 UTC, kks32 approved these changes

2019-11-26 04:08 UTC, merged