Initial condition for newton-raphson and checking for NaN for stress
cb-geo/mpm pull request #454
Opened 2019-08-05 06:53 UTC by ezrayst

- [x] Affine transformation might give initial condition of newton-raphson outside of [-1, 1], thus creating problems for particles near the edge of an element which might result in failure of finding the natural coordinates of the particle. Thus, initial condition is kept [-1, 1].
- [x] Stress computation from material is checked for NaN (not a number) which usually happens in case of zero divided by zero.

2019-08-05 22:38 UTC, kks32 requested changes

2019-08-05 22:38 UTC, kks32 commented on include/particle.tcc
> +
This is an expensive check to do every time, why is this happening?

2019-08-05 22:38 UTC, kks32 commented on include/cell.h
> +#include <math.h>
```suggestion
#include <cmath>
```

2019-08-05 22:45 UTC, ezrayst commented on include/particle.tcc
> +
Materials can give NaN stresses. I think I can omit it for this PR, but in MC model, we can have zero divided by zero case, which will give NaN stress, thus NaN acceleration, velocity and location.

2019-09-30 16:04 UTC, kks32 commented
On new branch `nr`

2019-09-30 16:04 UTC, closed without merging