Add return value for nodal friction and velocity constraints
cb-geo/mpm pull request #667
Opened 2020-07-09 03:23 UTC by ezrayst

**Describe the PR**
The current assign nodal constraints in `mpm_base` for both velocity and friction do not throw when the bool returns `false`. Therefore, this PR returns the bool and throw if `false`.

2020-07-09 03:32 UTC, bodhinandach submitted a review, later dismissed

2020-07-09 13:59 UTC, kks32 requested changes

2020-07-09 13:59 UTC, kks32 commented on include/solvers/mpm_base.tcc
> +                "Assign nodal velocity constraint is not properly assigned");
```suggestion
                "Nodal velocity constraint is not properly assigned");
```
otherwise the sentence is confusing.

2020-07-09 13:59 UTC, kks32 commented on include/solvers/mpm_base.tcc
> +                "Assign nodal friction constraint is not properly assigned");
```suggestion
                "Nodal friction constraint is not properly assigned");
```

2020-07-09 16:58 UTC, kks32 commented
@ezrayst Thanks. Could you please test the exception: https://github.com/catchorg/Catch2/blob/master/docs/assertions.md#exceptions

2020-07-09 23:53 UTC, kks32 approved these changes

2020-07-09 23:53 UTC, kks32 reviewed
Thanks Ezra!

2020-07-10 00:06 UTC, ezrayst commented
I want to discuss one more thing regarding this, let's use velocity constraints as example:
- `mpm_explicit` calls `bool` `initialise_mesh()` ([link](https://github.com/cb-geo/mpm/blob/a03af6cc5afa14c1b9e832b741e78a62eac89e46/include/solvers/mpm_base.tcc#L115))
- which in `mpm_base` calls `void` `nodal_velocity_constraints` [link](https://github.com/cb-geo/mpm/blob/a03af6cc5afa14c1b9e832b741e78a62eac89e46/include/solvers/mpm_base.tcc#L182) (I think the idea is to check for `NOTHROW` here right?)
- which in `constraints` calls `assign_nodal_velocity_constraint` [link](https://github.com/cb-geo/mpm/blob/9ed027de4fb58f4edf5866b1f25d08a4fbae887a/include/loads_bcs/constraints.tcc#L3). This function already has a throw that is tested. 

I do not think we need to check for `NOTHROW` for `nodal_velocity_constraints` in `mpm_base` anymore. I would leave it as is.

Further, this calls to change this function to a `void` instead of `bool`. What do you think?

2020-07-10 00:13 UTC, thiagordonho approved these changes

2020-07-10 16:53 UTC, kks32 commented
> I want to discuss one more thing regarding this, let's use velocity constraints as example:
> 
>     * `mpm_explicit` calls `bool` `initialise_mesh()` ([link](https://github.com/cb-geo/mpm/blob/a03af6cc5afa14c1b9e832b741e78a62eac89e46/include/solvers/mpm_base.tcc#L115))
> 
>     * which in `mpm_base` calls `void` `nodal_velocity_constraints` ([link](https://github.com/cb-geo/mpm/blob/a03af6cc5afa14c1b9e832b741e78a62eac89e46/include/solvers/mpm_base.tcc#L182)) (I think the idea is to check for `NOTHROW` here right?)
> 
>     * which in `constraints` calls `assign_nodal_velocity_constraint` ([link](https://github.com/cb-geo/mpm/blob/9ed027de4fb58f4edf5866b1f25d08a4fbae887a/include/loads_bcs/constraints.tcc#L3)). This function already has a throw that is tested.
> 
> 
> I do not think we need to check for `NOTHROW` for `nodal_velocity_constraints` in `mpm_base` anymore. I would leave it as is.
> 
> Further, this calls to change this function to a `void` instead of `bool`. What do you think?

If we want to address this issue, these functions should throw and abort on MPM main. There is no reason to continue when things fail.

2020-07-10 16:55 UTC, bodhinandach approved these changes
I think I am good with this. Unless @kks32 has any further request. Thanks @ezrayst

2020-07-10 18:04 UTC, merged