Refactor/particles properties
cb-geo/mpm pull request #673
Opened 2020-07-21 18:12 UTC by bodhinandach

**Describe the PR**
Adding container and general functions in node and particle_base for fluid and two-phase particle purposes.

**Related Issues/PRs**
#637, #650, and #654

**Additional context**
Due to the observed performance issue, the current containers and general functions in `node` and `particle_base` are added for `fluid` and `two_phase` particles without changing the solid_particle. Test should be added later in the PR of fluid and two-phase particles.

2020-07-21 18:42 UTC, kks32 requested changes
Thanks for the PR,  could you please make the minor cosmetic changes.

2020-07-21 18:42 UTC, kks32 commented on include/node.h
> +  double scalar_property(mpm::properties::Scalar property,
We need a retval

2020-07-21 18:42 UTC, kks32 commented on include/node.h
> +  virtual Eigen::Matrix<double, Tdim, 1> vector_property(
Add a \retval

2020-07-21 18:42 UTC, kks32 commented on include/node_base.h
> +  virtual double scalar_property(mpm::properties::Scalar property,
\retval

2020-07-21 18:42 UTC, kks32 commented on include/particles/particle_base.h
> +  double scalar_property(mpm::properties::Scalar property) const;
Add \retval

2020-07-21 18:42 UTC, kks32 commented on include/particles/particle_base.h
> +  double interpolate_scalar_property_nodes(mpm::properties::Scalar property,
Add \retval

2020-07-21 18:42 UTC, kks32 commented on include/particles/particle_base.tcc
> +void mpm::ParticleBase<Tdim>::map_scalar_property_nodes(
could we add `from` or `to` to the function names to make it clear?

2020-07-23 06:47 UTC, ezrayst reviewed
Thanks for this. I believe this is option (3) right from #654?

I have one question on this implementation in regards to `hdf5` and `resume` function. I guess there are enums and the IO would be done with no problem right?

2020-07-23 07:33 UTC, bodhinandach commented
@ezrayst This is for option (2). The option (3) is the PR #654 itself.

2020-07-23 07:46 UTC, ezrayst commented
Alright, but what about the `hdf5` and `resume` for fluid phase for instance?

2020-07-23 16:36 UTC, bodhinandach commented
> Alright, but what about the `hdf5` and `resume` for fluid phase for instance?

This will be implemented in the fluid or two-phase particles in the future PRs.

2020-07-28 21:33 UTC, closed without merging

2020-07-28 21:33 UTC, bodhinandach commented
@kks32 Should we delete this branch and archive `refactor/particles`