[Solver] MPM Explicit Modified Update Stress Last
cb-geo/mpm pull request #682
Opened 2020-08-03 05:09 UTC by bodhinandach

**Describe the PR**
This PR quickly adds the explicit MUSL solver capability in our `mpm_explicit` solver. I thought it will be useful as the `mpm::StressUpdate::MUSL` is available, though never be used. Due to its considerably slower performance, if you think the MUSL option is not necessary, let's remove the MUSL option.

**Additional context**
The MUSL option is basically similar to USL stress update, though require one more time momentum update right before recomputing strain_rate and strain for stress update. I ran the benchmark tests in both serial and parallel and both are ok! The necessity to do `map_momentum_to_nodes` and the `compute_velocity` one more time add a bit more computation time, so I am not sure if it is so useful. Here is the time comparison for the 3D hydrostatic column test in our benchmark test run in my local machine.

| Stress Update                   | Runtime (s) |
|--------------------------|-------------------|
| USF                  | 512.5            |
| USL | 505.4             |
| MUSL       | 560.2             |

2020-08-03 13:17 UTC, kks32 requested changes
Could we have separate functions inside MPMExplicit for USF, USL, MUSL. There will be some repetition, at least it would be clearer and we'll have fewer branching conditions

2020-08-03 15:13 UTC, bodhinandach commented
@kks32 I am okay. How you want to design or categorize them? I was thinking to call `initialise` node, `compute_mass_momentum`, and `compute_velocity` so that it was a set as the one done initially. However, the computational time becomes even slower as you do more mappings. Please feel free to commit your change @kks32.

2020-08-07 03:59 UTC, kks32 requested changes
Update to the newer format to include MUSL #685

2020-08-07 03:59 UTC, kks32 commented on include/solvers/mpm_explicit.tcc
> +#pragma omp parallel sections
Why do we need parallel sections here?

2020-08-10 18:00 UTC, bodhinandach commented
I am closing this PR and will reconsider the framework after looking at #685

2020-08-10 18:00 UTC, closed without merging