Linear Elastic Material Properties for #692
cb-geo/mpm pull request #705
Opened 2021-02-10 05:43 UTC by cgeudeker

**Describe the PR**
Add linear elastic material properties related to #692 .

**Related Issues/PRs**
Related to #692, specifically Kelvin-Voigt boundary.

**Additional context**
The following gives information that can also be found in the following [paper](https://elib.uni-stuttgart.de/bitstream/11682/513/1/Thesis_Issam_FinalPrint.pdf ). Kelvin-Voigt boundary elements operate as a dashpot, spring system according to the following equations.

![KV_boundary_eqs](https://user-images.githubusercontent.com/42182344/107469075-f1ce8800-6b1d-11eb-8174-d04c38ff51e0.png)

Equations for calculating P-wave (c_p) and S-wave (c_s) velocities:

![wave_velocities](https://user-images.githubusercontent.com/42182344/107469212-2e01e880-6b1e-11eb-834c-bdd10899c633.png)

Equations for calculating corresponding spring coefficients:

![spring_coeffs](https://user-images.githubusercontent.com/42182344/107469264-483bc680-6b1e-11eb-96ba-996fa4a3a4ae.png)

Additionally, constrained modulus and shear modulus were calculated. `layer_thickness` was the only value that could not be calculated by the already existent material properties.

Personal Notes:

I wasn't sure if there was a way to access the shear modulus that was calculated later in linear_elastic.tcc, so if there is please let me know. Also, I assumed that if `earthquake` was contained as a material property, so would `layer_thickness` , but if it would be preferred to also check that this value is contained here I'll switch that.

2021-02-14 13:03 UTC, kks32 requested changes

2021-02-14 13:03 UTC, kks32 commented on include/materials/linear_elastic.h
> +  double s_spring_coeff_{std::numeric_limits<double>::max()};
Remove all these lines as it is not good to store layer thickness in the material. Should be computed at the nodes.

2021-02-20 13:42 UTC, kks32 requested changes
In the PR description could you add how the input file would look like for the linear elastic part?

Instead of a separate boolean, maybe the best option would be to:
```
   "earthquake": {
       "shear_wave_velocity": 300,
       "compression_wave_velocity": 600
    }
```

2021-02-20 22:51 UTC, cgeudeker commented
@kks32 I updated the PR description. In short though, I felt that a boolean parameter worked better since it is just determining whether or not the P-wave and S-wave properties would be calculated. Alternatively though if we want to be able to input them as well, perhaps overwriting the calculation that would have been made otherwise than I think your approach would make more sense.

2021-02-22 22:45 UTC, kks32 commented
@cgeudeker The boolean doesn't do anything, you can set it to true and not actually define vs or vp.  I don't understand what you mean by ```Alternatively though if we want to be able to input them as well, perhaps overwriting the calculation that would have been made otherwise than I think your approach would make more sense.```?

2021-02-22 23:12 UTC, kks32 commented
https://github.com/cb-geo/mpm/blob/c9630b300f18d5cde87945e7f1ae8d1e7040d1cc/tests/materials/norsand_test.cc#L70 Reference for how to get a specific material property

2021-02-22 23:13 UTC, kks32 requested changes

2021-02-22 23:13 UTC, kks32 commented on include/materials/linear_elastic.tcc
> +      if (earthquake) {
```suggestion
```

2021-02-22 23:13 UTC, kks32 commented on include/materials/linear_elastic.tcc
> +    }
```suggestion
```

2021-02-25 10:27 UTC, kks32 requested changes

2021-02-25 10:27 UTC, kks32 commented on tests/materials/linear_elastic_test.cc
> +    jmaterial["p_wave_velocity"] = 116.023870223;
This is an incorrect text, you can't pass the values of p_wave and s_wave velocity and check if that's correct.

2021-02-25 10:27 UTC, kks32 commented on include/materials/linear_elastic.h
> +  double p_wave_velocity_{std::numeric_limits<double>::max()};
```suggestion
  //! Compressional Wave Velocity
  double vp_{std::numeric_limits<double>::max()};
  //! Shear wave Velocity
  double vs_{std::numeric_limits<double>::max()};
```

2021-02-25 10:27 UTC, kks32 commented on include/materials/linear_elastic.tcc
> +    s_wave_velocity_ = sqrt(shear_modulus / density_);
```suggestion
    vp_ = sqrt(constrained_modulus / density_);
    vs_ = sqrt(shear_modulus / density_);
```

2021-02-25 10:27 UTC, kks32 commented on include/materials/linear_elastic.tcc
> +
```suggestion
properties_["pwave_velocity"] = vp_;
properties_["swave_velocity"] = vs_;
```

2021-02-25 10:27 UTC, kks32 commented on tests/materials/linear_elastic_test.cc
> +    jmaterial["s_wave_velocity"] = 62.0173672946;
```suggestion
```

2021-02-25 10:27 UTC, kks32 commented on tests/materials/linear_elastic_test.cc
> +    auto material =
Check in 3D too

2021-03-02 21:09 UTC, kks32 approved these changes

2021-03-02 21:10 UTC, kks32 commented
@jgiven100 Hi Joel if you have some time could you please review this? I'm happy with the changes to calculate shear wave and compression wave velocities in Linear Elastic model

2021-03-02 23:47 UTC, jgiven100 approved these changes
@cgeudeker Thanks for adding `vs_` and `vp_` to the linear elastic model. This looks great!

@kks right now we don't have `linear elastic` documentation online (probably since the model only consists of an elastic tensor). Do we want to start a documentation page for `linear elastic` if we will be adding more features to the model for earthquake MPM?

2021-03-03 16:10 UTC, merged